function Gd2(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  stem x
%  Y1:  stem y

%  Auto-generated by MATLAB on 10-Nov-2018 17:12:25

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create stem
stem(X1,Y1);

% Create xlabel
xlabel('n','HorizontalAlignment','right','FontAngle','italic','FontSize',11,...
    'Interpreter','latex');

% Create ylabel
ylabel('f(n)','FontWeight','bold','FontAngle','italic',...
    'Interpreter','latex',...
    'HorizontalAlignment','left');

% Set the remaining axes properties
set(axes1,'XAxisLocation','origin','XGrid','on','YAxisLocation','origin',...
    'YGrid','on');
