function Gd3(X1, Y1, Z1)
%CREATEFIGURE(X1, Y1, Z1)
%  X1:  stem3 x
%  Y1:  stem3 y
%  Z1:  stem3 z

%  Auto-generated by MATLAB on 10-Nov-2018 17:18:54

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create stem3
stem3(X1,Y1,Z1);

% Create xlabel
xlabel('n','Interpreter','latex');

% Create zlabel
zlabel('Img(n)','Interpreter','latex');

% Create ylabel
ylabel('Real(n)','Interpreter','latex');

view(axes1,[-37.5 30]);
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'XAxisLocation','origin','YAxisLocation','origin');
